#docker compose file

version: "3.9"

services:
    myflasking:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: myflask
        ports:
          - "5000"
        #networks:
         #   - app-network
            
    myproxying:
        #build: 
         #  context: .
          #  dockerfile: dockerfilemyproxy
        image: "nginx"
        container_name: myproxy
        volumes:
            - ./docker_proxy/:/etc/nginx/conf.d/
        ports:
            - "5000:8082"
      #      - "443:443"
        #links:
         #  - "myflask:myproxy"
        #depends_on:
         #   - myflask
