#docker compose file

version: "3.9"

services:
    myflasking:
        build: 
            context: .
            dockerfile: Dockerfile
        image: project_test/myflask
        container_name: myflask
        ports:
          - "5000"
        #networks:
         #   - app-network
            
    myproxying:
        #build: 
         #  context: .
          #  dockerfile: dockerfilemyproxy
        image: nginx
        container_name: myproxy
        volumes:
            - ./docker_proxy/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
        #links:
         #  - "myflask:myproxy"
        #depends_on:
         #   - myflask
